### ISSUE TITLE
Add "publisher name" like busy and steemit do.

### ISSUE THREAD

**Issue by nothingismagick** [g-u-c/guc-desktop#21]
It would be a nice "finishing touch". 

![screen shot 2018-09-24 at 13 51 33](https://user-images.githubusercontent.com/35242872/45950656-0ec39880-c001-11e8-99f6-8a91a2595cea.png)

See where it says `3 Days ago - Busy` ?

For posts coming from the app it should say `3 Days ago - GUC Desktop`

**Comment by DrSensor** [comment]
Unfortunately, guc-desktop need to get listed on [steemscript](https://github.com/steemscript/steemscript/blob/master/apps.json) and wait for busy.org next release because [busy](https://github.com/busyorg/busy/blob/master/src/client/helpers/apps.js) use that as a whitelist.
